import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header/Header";
import ReactQuery from "@/components/ReactQuery";
import { Suspense } from 'react'


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Airbnb | Vacations",
  description: "Generated by create next app",
};

// Create a client

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode }>) {
  return (
    <ReactQuery>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Suspense fallback={<p>Loading...</p>}>

            <Header />
            <div className="  max-w-screen-xl mx-auto">
              {children}
            </div>
          </Suspense>

        </body>
      </html>
    </ReactQuery>

  );
}
